#!/usr/bin/env python3

from pueo.turfio import PueoTURFIO
import argparse
import glob
                                                      

parser = argparse.ArgumentParser()
parser.add_argument("turfionum", default=None,
                    help="Link to TURFIO # [1,2,4, or 5]")
parser.add_argument("--firmvers", default=None,
                    help="if specified, use TURFIO firmware version # [of form v_r_p_]")
args = parser.parse_args()

dev = PueoTURFIO(PueoTURFIO.find_serial_devices(int(args.turfionum))[0][0], 'SERIAL')

print("Linked to TURFIO "+args.turfionum)
   
if args.firmvers is None:
       mcs_list = glob.glob('/home/pueo/imgs/pueo_turfio_*.mcs').sort()[-1]
       vers_list = []
       for vers in mcs_list:
           curr_vers = vers.split('/home/pueo/imgs/pueo_turfio_')[1].split('.mcs')[0]
           vers_list.append(curr_vers)
       mcs_vers = '/home/pueo/imgs/pueo_turfio_'+vers_list[-1]+'.mcs'
       
else:
       mcs_vers = '/home/pueo/imgs/pueo_turfio_'+args.firmvers+'.mcs'

print("Using TURFIO firmware "+mcs_vers)

with dev.genspi as spi: 
    spi.program_mcs(mcs_vers)
